a = "H a r r y ! ! ! ! !! ! ! ! !! !!  ! "
print(len(a))
print(a.upper())
print(a.lower())
print(a.rstrip("!"))
print(a.replace("Harry", "John"))
print(a.split(" "))

para = "this is A line"
print(para.capitalize())
print(len(para))
print(para.center(30))
print(len(para.center(30)))
print(para.count("i"))
print(para.startswith("this", 0 , 6))
print(para.find("is"))
print(para.isalnum())
print(para.isalpha())
print(para.islower())
print(para.isprintable())
print(para.isspace())
print(para.istitle())
print(para.title())
print(para.swapcase())
