a = input("My name is : ")
print("Your name is", a)

x = int(input("1st num : "))
y = int(input("2nd num : "))
print("The value of ", x," + ", y, x + y)
print("The value of ", x," - ", y, x - y)
print("The value of ", x," * ", y, x * y)
print("The value of ", x," / ", y, x / y)
print("The value of ", x," // ", y, x // y)
